theme: jekyll-theme-minimal
title: Guido Draheim
description: IT professional and business consultant for a few decades / doing mostly DevOps consulting and deployment automation in the last years. / on Linux since 1996
logo: https://avatars2.githubusercontent.com/u/959453
